### ISSUE TITLE
Pre 1.0 releases

### ISSUE THREAD

**Issue by rakhimov** [ReliaQualAssociates/ramstk#66]
The current milestones look confusing considering the project's adherence to the semantic versioning.
1.0 looks like a 'big bang' release with 1.0{rc,beta} being big releases on their own.

- Why is there no pre-1.0 incremental releases?
- Why are dates & features fixed for milestones (this leaves '-1' degrees of freedom and not realistic)?

I suggest to start releasing 0.x versions incrementally.
For now, it would be helpful to freeze the feature addition and to focus on fixing bugs & rejuvenating the project code.

Also, I'd recommend to adapt either a) release when it's ready (a la Debian)
or b) release whatever on equal intervals (a la Linux).
1.0 should be about API stability guarantees rather than features.
This makes current 2.0 plans questionable. Are the 2.0 features going to break API?

**Comment by weibullguy** [comment]
If you're referencing the milestones I use to tag the issues, the dates are old and really were just placeholders.  Since I was the only one seeing them for so long, it wasn't a priority for me to change/delete them.  The Roadmap page in the wiki should be referenced for RTK plans moving forward.

Semantic versioning defines each component of the x.y.z as follows:

    x is the major version and must be incremented when making incompatible API changes.
    y is the minor version and must be incremented when adding backwards-compatible functionality.
    z is the patch version and must be incremented when making backwards-compatible bug fixes.

The current Master branch should be considered a prototype branch; I'd even consider it pre-0.y.z.  The code works on my machine, but it's a big bowl of pasta that needs to be untangled.  There is no API in the Master branch.

The Development branch is best considered the 0.y.z release.  The API is stabilizing and being  documented (http://rtk.readthedocs.io/en/develop/?badge=develop) as each RTK module is being updated to the current API.  I could provide a 0.y.z release after I update each RTK module (Revision => 0.1.0, Function => 0.2.0, Requirement => 0.3.0, etc.).  Since, as far as I know, the RTK user base is exactly one person (me), I wasn't terribly concerned about it.  I will begin releasing 0.y.z versions after each RTK module update; this will start with 0.4.0 when I finish the Validation module.

All of the features listed in the Roadmap for release 1.0.0 already exist in the Master branch.  Thus, all the work leading up to 1.0.0 is, in fact, fixing bugs (of which I don't write many, I just fix them when I find them) and rejuvenating the code (i.e., updating to the current API).  This is why 1.0.0 looks like a big release and it is.

Subsequent releases in the 1.y.z series will add functionality that will compatible with the current API.  Thus, the 1.1.0, 1.2.0, 1.3.0, etc. release cycle outlined in the Roadmap is compatible with semanitc versioning.

Release 2.0.0 may or may not break the current API.  Ideally, it won't, but the risk is there as the prime focus of 2.0.0 is adding graphical analyses.  Even if 2.0.0 breaks the current API, it remains consistent with semantic versioning.

The dates and features of the releases are not fixed.  The features listed in the Roadmap for each release are based on experience in the reliability field.  It's an outline of what organizations/people currently do in descending order of likelihood.  That is, cost analysis is rarely done or requested by a reliability organization (plan to add in 1.6.0) whereas RCM is quite popular (add in 1.1.0).

The only fixed date is the 1.0.0 release date of March 30, 2018.  Even that's not fixed, it's just the date I'm working towards and was established by building a schedule of remaining work to update RTK to the current API.  It's doable as long as not too many shiney objects distract me.  Beyond the 1.0.0 release, I plan on minor releases on a quarterly basis and patch releases as needed.  A major release would be timed to replace a minor release.

Fixing features and dates is how project management works.  In lieu of fixed features (objectives) and dates I'd be left with nothing but endless scope creep.  The safest place to be is on schedule, but you need a schedule to begin with.

**Comment by weibullguy** [comment]
Updated milestone 1.0.0 due date to March 30, 2018.  Deleted all other milestones.  At this time an issue will either be worked to support release 1.0.0 or a future release.
